version: "3"

services:
 db:
  image: mysql
  command: --default-authentication-plugin=mysql_native_password
  restart: always
  volumes:
   - db_data:/val/lib/mysql
   - ./init_db.sql:/data/app/init_db.sql
  environment:
   MYSQL_ROOT_PASSWORD: root_password
   MYSQL_USER: mysql_user
   MYSQL_PASSWORD: mysql_password
 
 node:
  depends_on:
   - db
  links:
   - "db:localhost"
  build: .
  restart: always
  ports:
   - 3000:3000

 adminer:
  image: adminer
  restart: always
  ports:
   - 8080:8080

volumes:
 db_data: {}
 init_db.sql: {}
